name: generate animation

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 

  # Allows manually running the job at any time
  workflow_dispatch:

  # Run on every push to the master/main branch
  push:
    branches:
      - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Generate the snake game SVG in both light and dark versions
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ratansagar
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      # Push the generated SVGs to the 'output' branch
      - name: Push generated SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
